version: '3.8'
services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - ./src/backend:/app

  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules



